CREATE TABLE EMPLEADO(
	CODIGO_EMP INT PRIMARY KEY IDENTITY,
	NOMBRE VARCHAR (45),
	FECHA_INGRESO DATETIME
)

INSERT INTO EMPLEADO VALUES('Carlos', '05-14-2019 14:13:56')

SELECT * FROM EMPLEADO


/*
BEGIN 
	DECLARE @FECHA DATETIME
	SET @FECHA = '05-14-2019 14:13:56'
	PRINT @FECHA
END
*/

CREATE PROCEDURE EJEMPLO_6_INSERTAR_EMPLEADO @NOMBRE_EMPLEADO VARCHAR(45), @FECHA_INGRESO DATETIME OUTPUT
AS
BEGIN
	INSERT INTO EMPLEADO VALUES (@NOMBRE_EMPLEADO, @FECHA_INGRESO)
END

EXEC EJEMPLO_6_INSERTAR_EMPLEADO 'Jaime', '08-27-2017 07:45:56';
EXEC EJEMPLO_6_INSERTAR_EMPLEADO 'Rafael', '04-07-2018 12:01:13';

SELECT * FROM EMPLEADO