CREATE TABLE PEDIDO(
	COD_PRODUCTO INT PRIMARY KEY IDENTITY,
	NOMBRE_PRODUCTO VARCHAR(30),
	CANT_PEDIDO INT,
	PRECIO_UNIT FLOAT,
	TOTAL FLOAT
)

CREATE PROCEDURE INGRESOP1 @NOMBRE VARCHAR(30), @CANTI INT, @PRECIO_UNIT FLOAT OUTPUT
AS
BEGIN
	DECLARE @TOTAL FLOAT = @PRECIO_UNIT * @CANTI;
	INSERT INTO PEDIDO VALUES (@NOMBRE, @CANTI, @PRECIO_UNIT, @TOTAL)
	EXEC INGRESOP2 @NOMBRE, @TOTAL
END

CREATE TABLE AUDITORIA(
	CODIGO INT PRIMARY KEY IDENTITY,
	PRODUCTO VARCHAR(30),
	TOTAL FLOAT
)

CREATE PROCEDURE INGRESOP2 @NOMBRE VARCHAR(30), @TOTAL FLOAT OUTPUT
AS
BEGIN 
	INSERT INTO AUDITORIA VALUES (@NOMBRE, @TOTAL)
END



EXEC INGRESOP1 'Pera',3,800.0

SELECT * FROM PEDIDO
SELECT * FROM AUDITORIA
